---

- hostname:
    name: "{{ inventory_hostname }}"

- name: Disable the selinux
  selinux:
    state: disabled

- name: Populate the nodes to /etc/hosts
  import_tasks: etchosts.yml

- name: include opensearch installation
  include: opensearch.yml

- name: include security plugin for opensearch
  include: security.yml

- name: Make sure opensearch is started
  service:
    name: opensearch
    state: started
    enabled: yes

- name: Get all the installed ES plugins
  command: "{{ es_plugin_bin_path }} list"
  register: list_plugins

- name: Show all the installed ES plugins
  debug:
    msg: "{{ list_plugins.stdout }}"

- name: Wait for opensearch to startup
  wait_for: host={{ hostvars[inventory_hostname]['ip'] }} port={{es_api_port}} delay=5 connect_timeout=1
