---
# defaults file for elasticsearch
es_java_install: true
update_java: false
es_use_repository: true
es_package_name: "elasticsearch-oss"
es_restart_on_change: true
es_start_service: false
es_group: "elasticsearch"
conf_dir: "/etc/elasticsearch"
es_api_port: 9200
es_api_host: "localhost"

es_nodes: |-
        {% for item in groups['es-cluster'] -%}
          {{ hostvars[item]['ip'] }}{% if not loop.last %}","{% endif %}
        {%- endfor %}

populate_inventory_to_hosts_file: true

es_plugin_bin_path: /usr/share/elasticsearch/bin/elasticsearch-plugin
es_sec_plugin_conf_path: /usr/share/elasticsearch/plugins/opendistro_security/securityconfig
es_sec_plugin_tools_path: /usr/share/elasticsearch/plugins/opendistro_security/tools

kibana_package_name: "kibana-oss"

es_nodes_kibana: |-
        {% for item in groups['es-cluster'] -%}
          https://{{ hostvars[item]['ip'] }}:{{ es_api_port }}{% if not loop.last %}","{% endif %}
        {%- endfor %}

kibana_plugin_bin_path: /usr/share/kibana/bin/kibana-plugin
