ca:
   root:
      dn: CN=root.ca.example.com,OU=CA,O=example.com\, Inc.,DC=example.com
      keysize: 2048
      validityDays: 730
      pkPassword: none
      file: root-ca.pem

### Default values and global settings
defaults:
      validityDays: 730
      pkPassword: none
      # Set this to true in order to generate config and certificates for
      # the HTTP interface of nodes
      httpsEnabled: true
      reuseTransportCertificatesForHttp: false
      verifyHostnames: false
      resolveHostnames: false


###
### Nodes
###
#
# Specify the nodes of your ES cluster here
#
nodes:
  - name: node-1
    dn: CN=node-1.example.com,OU=Ops,O=example.com\, Inc.,DC=example.com
    dns: node-1.example.com
    ip: 10.0.10.41

###
### Clients
###
#
# Specify the clients that shall access your ES cluster with certificate authentication here
#
# At least one client must be an admin user (i.e., a super-user). Admin users can
# be specified with the attribute admin: true
#
clients:
  - name: admin
    dn: CN=admin.example.com,OU=Ops,O=example.com\, Inc.,DC=example.com
    admin: true
