---

os_nodes: |-
        {% for item in groups['os-cluster'] -%}
          {{ item }}{% if not loop.last %}","{% endif %}
        {%- endfor %}

os_master_nodes: |-
        {% for item in groups['master'] -%}
          {{ item }}{% if not loop.last %}","{% endif %}
        {%- endfor %}

populate_inventory_to_hosts_file: true

os_plugin_bin_path: /usr/share/elasticsearch/bin/elasticsearch-plugin
os_sec_plugin_conf_path: /usr/share/elasticsearch/plugins/opendistro_security/securityconfig
os_sec_plugin_tools_path: /usr/share/elasticsearch/plugins/opendistro_security/tools
