version: '3.8'
services:
  keycloak:
    restart: on-failure
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${RDS_HOSTNAME_WITH_PORT}/keycloak
      KC_DB_USERNAME: keycloak
      KC_HOSTNAME_STRICT: false
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HTTPS_CERTIFICATE_FILE: /opt/certs/keycloak.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/certs/keycloak.key
      KC_FEATURES_DISABLED: 'admin-api,admin'
      KC_HEALTH_ENABLED: true
    command: start
    volumes:
      - /certs:/opt/certs
    ports:
      - 8443:8443
    logging:
      driver: awslogs
      options:
        awslogs-group: Keycloak/keycloak.log
        awslogs-create-group: 'true'
