---


## Admin user credentials will be used for User & Roles management and cluster operations
admin_password: Test@123

## Kibana server credentials will be used internally by the Kibana server
kibanaserver_password: Test@6789
