---

- hostname:
    name: "{{ inventory_hostname }}"

- name: Disable the selinux
  selinux:
    state: disabled

- name: Populate the nodes to /etc/hosts
  import_tasks: etchosts.yml

- name: include java.yml
  include: java.yml
  when: es_java_install

- name: include elasticsearch installation
  include: elasticsearch.yml

- name: include opendistro security plugin for elasticsearch
  include: opendistro_security.yml
  when: opendistro_security_install

- name: include opendistro alerting plugin for elasticsearch
  include: opendistro_alerting.yml
  when: opendistro_alerting_install

- name: include opendistro sql plugin for elasticsearch
  include: opendistro_sql.yml
  when: opendistro_sql_install

- name: include opendistro ism plugin for elasticsearch
  include: opendistro_ism.yml
  when: opendistro_ism_install

- name: include opendistro Anomaly Detection plugin for elasticsearch
  include: opendistro_ad.yml
  when: opendistro_ad_install

- name: include opendistro Asynchronous search plugin for elasticsearch
  include: opendistro_asyncsearch.yml
  when: opendistro_asyncsearch_install

- name: include opendistro Reports scheduler plugin for elasticsearch
  include: opendistro_reports_scheduler.yml
  when: opendistro_reports_scheduler_install

- name: Get all the installed ES plugins
  command: "{{ es_plugin_bin_path }} list"
  register: list_plugins

- name: Show all the installed ES plugins
  debug:
    msg: "{{ list_plugins.stdout }}"

- name: Wait for elasticsearch to startup
  wait_for: host={{ hostvars[inventory_hostname]['ip'] }} port={{es_api_port}} delay=5 connect_timeout=1
