---

- name: Anomaly Detection Plugin Install | Download Opendistro Elasticsearch ad plugin {{ opendistro_ad_plugin_version }}
  get_url:
    url: "{{ opendistro_plugin_url }}{{ opendistro_ad_download_url }}opendistro-anomaly-detection-{{ opendistro_ad_plugin_version }}.zip"
    dest: "{{ es_home }}/opendistro-anomaly-detection-{{ opendistro_ad_plugin_version }}.zip"
  register: download

- name: Anomaly Detection Plugin Install | Install the Opendistro ad plugin
  command: "{{ es_plugin_bin_path }} install -b file://{{ es_home }}/opendistro-anomaly-detection-{{ opendistro_ad_plugin_version }}.zip"
  when: download.changed
  notify: restart elasticsearch
