---

- name: Job Scheduler Plugin Install | Download Opendistro Elasticsearch JS plugin {{ opendistro_js_plugin_version }}
  get_url:
    url: "{{ opendistro_plugin_url }}{{ opendistro_js_download_url }}opendistro-job-scheduler-{{ opendistro_js_plugin_version }}.zip"
    dest: "{{ es_home }}/opendistro-job-scheduler-{{ opendistro_js_plugin_version }}.zip"
  register: download_js

- name: Job Scheduler Plugin Install | Install the Opendistro JS plugin
  command: "{{ es_plugin_bin_path }} install -b file://{{ es_home }}/opendistro-job-scheduler-{{ opendistro_js_plugin_version }}.zip"
  when: download_js.changed

- name: ISM Plugin Install | Download Opendistro Elasticsearch ism plugin {{ opendistro_ism_plugin_version }}
  get_url:
    url: "{{ opendistro_plugin_url }}{{ opendistro_ism_download_url }}opendistro-index-management-{{ opendistro_ism_plugin_version }}.zip"
    dest: "{{ es_home }}/opendistro-index-management-{{ opendistro_ism_plugin_version }}.zip"
  register: download

- name: ISM Plugin Install | Install the Opendistro ism plugin
  command: "{{ es_plugin_bin_path }} install -b file://{{ es_home }}/opendistro-index-management-{{ opendistro_ism_plugin_version }}.zip"
  when: download.changed
  notify: restart elasticsearch
