---

- name: sql Plugin Install | Download Opendistro Elasticsearch sql plugin {{ opendistro_sql_plugin_version }}
  get_url:
    url: "{{ opendistro_plugin_url }}{{ opendistro_sql_download_url }}opendistro-sql-{{ opendistro_sql_plugin_version }}.zip"
    dest: "{{ es_home }}/opendistro-sql-{{ opendistro_sql_plugin_version }}.zip"
  register: download

- name: sql Plugin Install | Install the Opendistro sql plugin
  command: "{{ es_plugin_bin_path }} install -b file://{{ es_home }}/opendistro-sql-{{ opendistro_sql_plugin_version }}.zip"
  when: download.changed
  notify: restart elasticsearch
