apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
data:
  log4j2.properties: |-
{{ .Values.opensearch.global.log4jConfig | indent 4 }}
  notebooks.yml: |-
{{ .Values.opensearch.global.opensearchNotebook | indent 4 }}
  reports-scheduler.yml: |-
{{ .Values.opensearch.global.opensearchReports | indent 4 }}
  opensearch.yml: |
    # Bind to all interfaces because we don't know what IP address Docker will assign to us.
    network.host: 0.0.0.0

    cluster.name: {{ .Values.opensearch.global.clusterName }}

    {{ if .Values.opensearch.master.roles }}
    cluster.initial_master_nodes: {{ template "initial-master-nodes" . }}
    {{ else }}
    # cluster.initial_master_nodes: {{ template "initial-master-nodes" . }}
    {{ end }}

    # # minimum_master_nodes need to be explicitly set when bound on a public IP
    # # set to 1 to allow single node clusters
        
    {{ if .Values.opensearch.master.roles }}
    # discovery.zen.minimum_master_nodes: 1
    {{ else }}
    discovery.zen.minimum_master_nodes: 1
    {{ end }}
    
    node.roles: ${ROLES}
    discovery.seed_hosts: ${SEEDS}

    # Setting network.host to a non-loopback address enables the annoying bootstrap checks. "Single-node" mode disables them again.
    {{ if .Values.opensearch.master.roles }}
    #discovery.type: single-node
    {{ else }}
    discovery.type: single-node
    {{ end }}

    plugins.security.ssl.transport.pemcert_filepath: ssl/transport/tls.crt
    plugins.security.ssl.transport.pemkey_filepath: ssl/transport/tls.key
    plugins.security.ssl.transport.pemtrustedcas_filepath: ssl/transport/ca.crt
    plugins.security.ssl.transport.enforce_hostname_verification: false

    {{ if .Values.opensearch.global.ssl.rest.enabled }}
    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemcert_filepath: ssl/rest/tls.crt
    plugins.security.ssl.http.pemkey_filepath: ssl/rest/tls.key
    plugins.security.ssl.http.pemtrustedcas_filepath: ssl/rest/ca.crt
    {{ end }}

    plugins.security.allow_unsafe_democertificates: false
    plugins.security.allow_default_init_securityindex: true

    {{ if .Values.opensearch.global.ssl.admin.enabled }}
    plugins.security.authcz.admin_dn:
      - {{ .Values.opensearch.global.ssl.admin.commonName }}
    {{ end }}

    plugins.security.nodes_dn:
      - {{ .Values.opensearch.global.ssl.transport.commonName }}

    plugins.security.audit.type: internal_opensearch
    plugins.security.enable_snapshot_restore_privilege: true
    plugins.security.check_snapshot_restore_write_privileges: true
    plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
    plugins.security.system_indices.enabled: true
    plugins.security.system_indices.indices: [".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opendistro-asynchronous-search-response*"]
    {{ .Values.opensearch.global.additionalConfig }}
  jvm.options: |
    ## JVM configuration

    ################################################################
    ## IMPORTANT: JVM heap size
    ################################################################
    ##
    ## You should always set the min and max JVM heap
    ## size to the same value. For example, to set
    ## the heap to 4 GB, set:
    ##
    ## -Xms4g
    ## -Xmx4g
    ##
    ## See https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
    ## for more information
    ##
    ################################################################

    # Xms represents the initial size of total heap space
    # Xmx represents the maximum size of total heap space

    -Xms1g
    -Xmx1g

    ################################################################
    ## Expert settings
    ################################################################
    ##
    ## All settings below this section are considered
    ## expert settings. Don't tamper with them unless
    ## you understand what you are doing
    ##
    ################################################################

    ## GC configuration
    8-13:-XX:+UseConcMarkSweepGC
    8-13:-XX:CMSInitiatingOccupancyFraction=75
    8-13:-XX:+UseCMSInitiatingOccupancyOnly

    ## G1GC Configuration
    # NOTE: G1 GC is only supported on JDK version 10 or later
    # to use G1GC, uncomment the next two lines and update the version on the
    # following three lines to your version of the JDK
    # 10-13:-XX:-UseConcMarkSweepGC
    # 10-13:-XX:-UseCMSInitiatingOccupancyOnly
    14-:-XX:+UseG1GC
    14-:-XX:G1ReservePercent=25
    14-:-XX:InitiatingHeapOccupancyPercent=30

    ## JVM temporary directory
    -Djava.io.tmpdir=${OPENSEARCH_TMPDIR}

    ## heap dumps

    # generate a heap dump when an allocation from the Java heap fails
    # heap dumps are created in the working directory of the JVM
    -XX:+HeapDumpOnOutOfMemoryError

    # specify an alternative path for heap dumps; ensure the directory exists and
    # has sufficient space
    -XX:HeapDumpPath=data

    # specify an alternative path for JVM fatal error logs
    -XX:ErrorFile=logs/hs_err_pid%p.log

    ## JDK 8 GC logging
    8:-XX:+PrintGCDetails
    8:-XX:+PrintGCDateStamps
    8:-XX:+PrintTenuringDistribution
    8:-XX:+PrintGCApplicationStoppedTime
    8:-Xloggc:logs/gc.log
    8:-XX:+UseGCLogFileRotation
    8:-XX:NumberOfGCLogFiles=32
    8:-XX:GCLogFileSize=64m

    # JDK 9+ GC logging
    9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m

    ## OpenDistro Performance Analyzer
    -Dclk.tck=100
    -Djdk.attach.allowAttachSelf=true
    -Djava.security.policy=/usr/share/opensearch/plugins/opensearch-performance-analyzer/pa_config/opensearch_security.policy  