---

- name: Elasticsearch with opendistro configuration
  hosts: es-cluster
  gather_facts: false
  roles:
    - { role: centos7/elasticsearch_opendistro }

- name: Kibana with opendistro configuration
  hosts: kibana
  gather_facts: false
  roles:
    - { role: centos7/kibana_opendistro }
