name: Index data to opensearch cluster

on:
  workflow_call:
    inputs:
      endpoint:
        required: true
        description: 'OpenSearch cluster endpoint'
        type: string
      opensearch-manifest-url:
        required: true
        description: 'OpenSearch Manifest URL'
        type: string
      opensearch-dashboards-manifest-url:
        required: true
        description: 'OpenSearch Dashboards URL'
        type: string
    secrets:
      opensearch-user:
        required: true
      opensearch-password:
        required: true

jobs:   
  index-data:
    runs-on: ubuntu-latest
    steps:
      - name: Index data
        id: dist-manifests
        run: |
          wget ${{ inputs.opensearch-manifest-url }} -O opensearch.yml
          wget ${{ inputs.opensearch-dashboards-manifest-url }} -O opensearch-dashboards.yml
          yq -o=json '.' opensearch.yml > opensearch.json
          yq -o=json '.' opensearch-dashboards.yml > dashboards.json

          curl -X POST "https://${{inputs.endpoint}}:8443/opensearch/_doc/1" -H "Content-Type: application/json" -d @opensearch.json -u ${{ secrets.opensearch-user }}:${{ secrets.opensearch-password }} --insecure

          curl -X POST "https://${{inputs.endpoint}}:8443/opensearch-dashboards/_doc/1" -H "Content-Type: application/json" -d @dashboards.json -u ${{ secrets.opensearch-user }}:${{ secrets.opensearch-password }} --insecure