name: Nightly Playground Build and Test

on:
  pull_request:
    paths:
      - nightly-playground/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nightly-playground

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 16.x
  
      - name: Run CDK Build and Test
        run: |
          npm install
          npm run build

      - name: Run test coverage
        run: |
          npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3
