---

- name: ISM Plugin Install | Download Opendistro Kibana ism plugin {{ opendistro_ism_kibana_plugin_version }}
  get_url:
    url: "{{ opendistro_plugin_url }}{{ opendistro_ism_kibana_download_url }}opendistroIndexManagementKibana-{{ opendistro_ism_kibana_plugin_version }}.zip"
    dest: "/usr/share/kibana/opendistro-ism-{{ opendistro_ism_kibana_plugin_version }}.zip"
  register: download

- name: ISM Plugin Install | Install the Opendistro ism plugin in kibana
  command: "sudo -u kibana {{ kibana_plugin_bin_path }} install file:///usr/share/kibana/opendistro-ism-{{ opendistro_ism_kibana_plugin_version }}.zip"
  when: download.changed
  notify: restart kibana
