---

- name: alerting Plugin Install | Download Opendistro Kibana alerting plugin {{ opendistro_alerting_kibana_plugin_version }}
  get_url:
    url: "{{ opendistro_plugin_url }}{{ opendistro_alerting_kibana_download_url }}opendistroAlertingKibana-{{ opendistro_alerting_kibana_plugin_version }}.zip"
    dest: "/usr/share/kibana/opendistro-alerting-{{ opendistro_alerting_kibana_plugin_version }}.zip"
  register: download

- name: alerting Plugin Install | Install the Opendistro alerting plugin in kibana
  command: "sudo -u kibana {{ kibana_plugin_bin_path }} install file:///usr/share/kibana/opendistro-alerting-{{ opendistro_alerting_kibana_plugin_version }}.zip"
  when: download.changed
  notify: restart kibana
