---

- name: AD Plugin Install | Download Opendistro Kibana Anomaly Detection plugin {{ opendistro_ad_kibana_plugin_version }}
  get_url:
    url: "{{ opendistro_plugin_url }}{{ opendistro_ad_kibana_download_url }}opendistroAnomalyDetectionKibana-{{ opendistro_ad_kibana_plugin_version }}.zip"
    dest: "/usr/share/kibana/opendistro-ad-{{ opendistro_ad_kibana_plugin_version }}.zip"
  register: download

- name: AD Plugin Install | Install the Opendistro Anomaly Detection plugin in kibana
  command: "sudo -u kibana {{ kibana_plugin_bin_path }} install file:///usr/share/kibana/opendistro-ad-{{ opendistro_ad_kibana_plugin_version }}.zip"
  when: download.changed
  notify: restart kibana
